//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.ProxyWMS_UI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOCommand", Namespace="http://schemas.datacontract.org/2004/07/i2MFCS.WMS.Database.DTO")]
    [System.SerializableAttribute()]
    public partial class DTOCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserInterface.ProxyWMS_UI.CommandCommandStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TU_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserInterface.ProxyWMS_UI.CommandCommandStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TU_ID {
            get {
                return this.TU_IDField;
            }
            set {
                if ((this.TU_IDField.Equals(value) != true)) {
                    this.TU_IDField = value;
                    this.RaisePropertyChanged("TU_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command.CommandStatus", Namespace="http://schemas.datacontract.org/2004/07/i2MFCS.WMS.Database.Tables")]
    public enum CommandCommandStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotActive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finished = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOOrder", Namespace="http://schemas.datacontract.org/2004/07/i2MFCS.WMS.Database.DTO")]
    [System.SerializableAttribute()]
    public partial class DTOOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ERP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKU_BatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKU_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SKU_QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubOrderNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ERP_ID {
            get {
                return this.ERP_IDField;
            }
            set {
                if ((this.ERP_IDField.Equals(value) != true)) {
                    this.ERP_IDField = value;
                    this.RaisePropertyChanged("ERP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseTime {
            get {
                return this.ReleaseTimeField;
            }
            set {
                if ((this.ReleaseTimeField.Equals(value) != true)) {
                    this.ReleaseTimeField = value;
                    this.RaisePropertyChanged("ReleaseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU_Batch {
            get {
                return this.SKU_BatchField;
            }
            set {
                if ((object.ReferenceEquals(this.SKU_BatchField, value) != true)) {
                    this.SKU_BatchField = value;
                    this.RaisePropertyChanged("SKU_Batch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU_ID {
            get {
                return this.SKU_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.SKU_IDField, value) != true)) {
                    this.SKU_IDField = value;
                    this.RaisePropertyChanged("SKU_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SKU_Qty {
            get {
                return this.SKU_QtyField;
            }
            set {
                if ((this.SKU_QtyField.Equals(value) != true)) {
                    this.SKU_QtyField = value;
                    this.RaisePropertyChanged("SKU_Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubOrderID {
            get {
                return this.SubOrderIDField;
            }
            set {
                if ((this.SubOrderIDField.Equals(value) != true)) {
                    this.SubOrderIDField = value;
                    this.RaisePropertyChanged("SubOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubOrderName {
            get {
                return this.SubOrderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubOrderNameField, value) != true)) {
                    this.SubOrderNameField = value;
                    this.RaisePropertyChanged("SubOrderName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyWMS_UI.IWMSToUI")]
    public interface IWMSToUI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/GetCommands", ReplyAction="http://tempuri.org/IWMSToUI/GetCommandsResponse")]
        UserInterface.ProxyWMS_UI.DTOCommand[] GetCommands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/GetCommands", ReplyAction="http://tempuri.org/IWMSToUI/GetCommandsResponse")]
        System.Threading.Tasks.Task<UserInterface.ProxyWMS_UI.DTOCommand[]> GetCommandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/CancelOrder", ReplyAction="http://tempuri.org/IWMSToUI/CancelOrderResponse")]
        void CancelOrder(UserInterface.ProxyWMS_UI.DTOOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/CancelOrder", ReplyAction="http://tempuri.org/IWMSToUI/CancelOrderResponse")]
        System.Threading.Tasks.Task CancelOrderAsync(UserInterface.ProxyWMS_UI.DTOOrder order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/BlockLocations", ReplyAction="http://tempuri.org/IWMSToUI/BlockLocationsResponse")]
        void BlockLocations(string locStartsWith, bool block, int reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/BlockLocations", ReplyAction="http://tempuri.org/IWMSToUI/BlockLocationsResponse")]
        System.Threading.Tasks.Task BlockLocationsAsync(string locStartsWith, bool block, int reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/BlockTU", ReplyAction="http://tempuri.org/IWMSToUI/BlockTUResponse")]
        void BlockTU(int TUID, bool block, int reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSToUI/BlockTU", ReplyAction="http://tempuri.org/IWMSToUI/BlockTUResponse")]
        System.Threading.Tasks.Task BlockTUAsync(int TUID, bool block, int reason);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWMSToUIChannel : UserInterface.ProxyWMS_UI.IWMSToUI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WMSToUIClient : System.ServiceModel.ClientBase<UserInterface.ProxyWMS_UI.IWMSToUI>, UserInterface.ProxyWMS_UI.IWMSToUI {
        
        public WMSToUIClient() {
        }
        
        public WMSToUIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WMSToUIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSToUIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSToUIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UserInterface.ProxyWMS_UI.DTOCommand[] GetCommands() {
            return base.Channel.GetCommands();
        }
        
        public System.Threading.Tasks.Task<UserInterface.ProxyWMS_UI.DTOCommand[]> GetCommandsAsync() {
            return base.Channel.GetCommandsAsync();
        }
        
        public void CancelOrder(UserInterface.ProxyWMS_UI.DTOOrder order) {
            base.Channel.CancelOrder(order);
        }
        
        public System.Threading.Tasks.Task CancelOrderAsync(UserInterface.ProxyWMS_UI.DTOOrder order) {
            return base.Channel.CancelOrderAsync(order);
        }
        
        public void BlockLocations(string locStartsWith, bool block, int reason) {
            base.Channel.BlockLocations(locStartsWith, block, reason);
        }
        
        public System.Threading.Tasks.Task BlockLocationsAsync(string locStartsWith, bool block, int reason) {
            return base.Channel.BlockLocationsAsync(locStartsWith, block, reason);
        }
        
        public void BlockTU(int TUID, bool block, int reason) {
            base.Channel.BlockTU(TUID, block, reason);
        }
        
        public System.Threading.Tasks.Task BlockTUAsync(int TUID, bool block, int reason) {
            return base.Channel.BlockTUAsync(TUID, block, reason);
        }
    }
}
