//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterfaceGravityPanel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserInterfaceGravityPanel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string Color1 {
            get {
                return ResourceManager.GetString("Color1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Color2 {
            get {
                return ResourceManager.GetString("Color2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Color3 {
            get {
                return ResourceManager.GetString("Color3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        public static string Color4 {
            get {
                return ResourceManager.GetString("Color4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Color5 {
            get {
                return ResourceManager.GetString("Color5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Color6 {
            get {
                return ResourceManager.GetString("Color6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkCyan.
        /// </summary>
        public static string Color7 {
            get {
                return ResourceManager.GetString("Color7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DimGray.
        /// </summary>
        public static string Color8 {
            get {
                return ResourceManager.GetString("Color8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current order.
        /// </summary>
        public static string CurrentOrder {
            get {
                return ResourceManager.GetString("CurrentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet to take.
        /// </summary>
        public static string FirstTU {
            get {
                return ResourceManager.GetString("FirstTU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed.
        /// </summary>
        public static string InitFailed {
            get {
                return ResourceManager.GetString("InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane.
        /// </summary>
        public static string Lane {
            get {
                return ResourceManager.GetString("Lane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. pallets.
        /// </summary>
        public static string NoTUs {
            get {
                return ResourceManager.GetString("NoTUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck:.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string OrderStatus0 {
            get {
                return ResourceManager.GetString("OrderStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string OrderStatus1 {
            get {
                return ResourceManager.GetString("OrderStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On target.
        /// </summary>
        public static string OrderStatus2 {
            get {
                return ResourceManager.GetString("OrderStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On target partial.
        /// </summary>
        public static string OrderStatus3 {
            get {
                return ResourceManager.GetString("OrderStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string OrderStatus4 {
            get {
                return ResourceManager.GetString("OrderStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string OrderStatus5 {
            get {
                return ResourceManager.GetString("OrderStatus5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMP.
        /// </summary>
        public static string Ramp {
            get {
                return ResourceManager.GetString("Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh failed.
        /// </summary>
        public static string RefreshFailed {
            get {
                return ResourceManager.GetString("RefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string ShortActive {
            get {
                return ResourceManager.GetString("ShortActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string ShortAll {
            get {
                return ResourceManager.GetString("ShortAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string ShortDone {
            get {
                return ResourceManager.GetString("ShortDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string SKUBatch {
            get {
                return ResourceManager.GetString("SKUBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string SKUID {
            get {
                return ResourceManager.GetString("SKUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string SKUQty {
            get {
                return ResourceManager.GetString("SKUQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        public static string SubOrderID {
            get {
                return ResourceManager.GetString("SubOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string TUID {
            get {
                return ResourceManager.GetString("TUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string TUSubOrderID {
            get {
                return ResourceManager.GetString("TUSubOrderID", resourceCulture);
            }
        }
    }
}
