//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public int ID { get; set; }
        public string AlarmID { get; set; }
        public System.DateTime ArrivedTime { get; set; }
        public Nullable<System.DateTime> AckTime { get; set; }
        public Nullable<System.DateTime> RemovedTime { get; set; }
        public Alarm.EnumAlarmStatus Status { get; set; }
        public Alarm.EnumAlarmSeverity Severity { get; set; }
        public string Unit { get; set; }
    }
}
