//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public Event.EnumSeverity Severity { get; set; }
        public Event.EnumType Type { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
    }
}
