//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int ID { get; set; }
        public int Material { get; set; }
        public string Position { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<EnumMovementTask> Task { get; set; }
    
        public virtual MaterialID MaterialID { get; set; }
    }
}
