//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleConveyorCommand : SimpleCommand
    {
        public string Target { get; set; }
    
        public virtual PlaceID PlaceID2 { get; set; }
    }
}
