//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Communication.TelegramsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TelegramsService.ITelegramNotify", CallbackContract=typeof(Communication.TelegramsService.ITelegramNotifyCallback))]
    public interface ITelegramNotify {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/RegisterCommunicator", ReplyAction="http://tempuri.org/ITelegramNotify/RegisterCommunicatorResponse")]
        void RegisterCommunicator(string communicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/RegisterCommunicator", ReplyAction="http://tempuri.org/ITelegramNotify/RegisterCommunicatorResponse")]
        System.Threading.Tasks.Task RegisterCommunicatorAsync(string communicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/UnRegisterCommunicator", ReplyAction="http://tempuri.org/ITelegramNotify/UnRegisterCommunicatorResponse")]
        void UnRegisterCommunicator(string communicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/UnRegisterCommunicator", ReplyAction="http://tempuri.org/ITelegramNotify/UnRegisterCommunicatorResponse")]
        System.Threading.Tasks.Task UnRegisterCommunicatorAsync(string communicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/TelegramNotifyRcv", ReplyAction="http://tempuri.org/ITelegramNotify/TelegramNotifyRcvResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportSetTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramLife))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramACK))]
        void TelegramNotifyRcv(Telegrams.Telegram tel, string communicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/TelegramNotifyRcv", ReplyAction="http://tempuri.org/ITelegramNotify/TelegramNotifyRcvResponse")]
        System.Threading.Tasks.Task TelegramNotifyRcvAsync(Telegrams.Telegram tel, string communicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/TelegramNotifySend", ReplyAction="http://tempuri.org/ITelegramNotify/TelegramNotifySendResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportSetTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramLife))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramACK))]
        void TelegramNotifySend(Telegrams.Telegram tel, string communicatorName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/TelegramNotifySend", ReplyAction="http://tempuri.org/ITelegramNotify/TelegramNotifySendResponse")]
        System.Threading.Tasks.Task TelegramNotifySendAsync(Telegrams.Telegram tel, string communicatorName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITelegramNotifyCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/TelegramSend", ReplyAction="http://tempuri.org/ITelegramNotify/TelegramSendResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportSetTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramLife))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramACK))]
        void TelegramSend(Telegrams.Telegram tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelegramNotify/LongTelegramSendWait", ReplyAction="http://tempuri.org/ITelegramNotify/LongTelegramSendWaitResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramCraneTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramTransportSetTime))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramLife))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Telegrams.TelegramACK))]
        bool LongTelegramSendWait(Telegrams.Telegram tel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITelegramNotifyChannel : Communication.TelegramsService.ITelegramNotify, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TelegramNotifyClient : System.ServiceModel.DuplexClientBase<Communication.TelegramsService.ITelegramNotify>, Communication.TelegramsService.ITelegramNotify {
        
        public TelegramNotifyClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TelegramNotifyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TelegramNotifyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TelegramNotifyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TelegramNotifyClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterCommunicator(string communicatorName) {
            base.Channel.RegisterCommunicator(communicatorName);
        }
        
        public System.Threading.Tasks.Task RegisterCommunicatorAsync(string communicatorName) {
            return base.Channel.RegisterCommunicatorAsync(communicatorName);
        }
        
        public void UnRegisterCommunicator(string communicatorName) {
            base.Channel.UnRegisterCommunicator(communicatorName);
        }
        
        public System.Threading.Tasks.Task UnRegisterCommunicatorAsync(string communicatorName) {
            return base.Channel.UnRegisterCommunicatorAsync(communicatorName);
        }
        
        public void TelegramNotifyRcv(Telegrams.Telegram tel, string communicatorName) {
            base.Channel.TelegramNotifyRcv(tel, communicatorName);
        }
        
        public System.Threading.Tasks.Task TelegramNotifyRcvAsync(Telegrams.Telegram tel, string communicatorName) {
            return base.Channel.TelegramNotifyRcvAsync(tel, communicatorName);
        }
        
        public void TelegramNotifySend(Telegrams.Telegram tel, string communicatorName) {
            base.Channel.TelegramNotifySend(tel, communicatorName);
        }
        
        public System.Threading.Tasks.Task TelegramNotifySendAsync(Telegrams.Telegram tel, string communicatorName) {
            return base.Channel.TelegramNotifySendAsync(tel, communicatorName);
        }
    }
}
