//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.WMSConsumerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WMSConsumerServiceReference.IWMSConsumer")]
    public interface IWMSConsumer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSConsumer/WMS_Status", ReplyAction="http://tempuri.org/IWMSConsumer/WMS_StatusResponse")]
        string WMS_Status(string wmsID, string item, string status, string info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWMSConsumer/WMS_Status", ReplyAction="http://tempuri.org/IWMSConsumer/WMS_StatusResponse")]
        System.Threading.Tasks.Task<string> WMS_StatusAsync(string wmsID, string item, string status, string info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWMSConsumerChannel : Warehouse.WMSConsumerServiceReference.IWMSConsumer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WMSConsumerClient : System.ServiceModel.ClientBase<Warehouse.WMSConsumerServiceReference.IWMSConsumer>, Warehouse.WMSConsumerServiceReference.IWMSConsumer {
        
        public WMSConsumerClient() {
        }
        
        public WMSConsumerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WMSConsumerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSConsumerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WMSConsumerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WMS_Status(string wmsID, string item, string status, string info) {
            return base.Channel.WMS_Status(wmsID, item, status, info);
        }
        
        public System.Threading.Tasks.Task<string> WMS_StatusAsync(string wmsID, string item, string status, string info) {
            return base.Channel.WMS_StatusAsync(wmsID, item, status, info);
        }
    }
}
