//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUs
    {
        public int TU_ID { get; set; }
        public string SKU_ID { get; set; }
        public double Qty { get; set; }
        public string Batch { get; set; }
        public System.DateTime ProdDate { get; set; }
        public System.DateTime ExpDate { get; set; }
    
        public virtual SKU_ID SKU_ID1 { get; set; }
        public virtual TU_ID TU_ID1 { get; set; }
    }
}
